### ISSUE TITLE
Database unit test 

### ISSUE THREAD

**Issue by SaberDoTcodeR** [oxydev/SubsCrypt-nodejs-backend#17]
- [x] add database unit test 
- [x] add profile manager unit test
- [x] improve code coverage in other sections

**Comment by HadiEsna** [comment]
We've reached this result in test
We covered all functionalities.

<pre>
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |   84.11 |       60 |   78.57 |   84.11 |                   
 src               |   97.87 |       75 |      50 |   97.87 |                   
  logger.js        |      90 |      100 |      50 |      90 | 10                
  routes.js        |     100 |      100 |     100 |     100 |                   
  server.js        |     100 |       50 |     100 |     100 | 15                
 ...atabaseWrapper |     100 |      100 |     100 |     100 |                   
  database.js      |     100 |      100 |     100 |     100 |                   
 src/docs          |     100 |      100 |     100 |     100 |                   
  basicInfo.js     |     100 |      100 |     100 |     100 |                   
  components.js    |     100 |      100 |     100 |     100 |                   
  index.js         |     100 |      100 |     100 |     100 |                   
  servers.js       |     100 |      100 |     100 |     100 |                   
  tags.js          |     100 |      100 |     100 |     100 |                   
 ...docs/subscrypt |     100 |      100 |     100 |     100 |                   
  checkAuth.js     |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
  ...bscription.js |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
  ...cteristics.js |     100 |      100 |     100 |     100 |                   
  getPlanData.js   |     100 |      100 |     100 |     100 |                   
  getPlanLength.js |     100 |      100 |     100 |     100 |                   
  getUsername.js   |     100 |      100 |     100 |     100 |                   
  index.js         |     100 |      100 |     100 |     100 |                   
  isConnected.js   |     100 |      100 |     100 |     100 |                   
  ...eAvailable.js |     100 |      100 |     100 |     100 |                   
  ...rCheckAuth.js |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
  userCheckAuth.js |     100 |      100 |     100 |     100 |                   
  ...thUsername.js |     100 |      100 |     100 |     100 |                   
 src/errors        |     100 |      100 |     100 |     100 |                   
  index.js         |     100 |      100 |     100 |     100 |                   
  index.test-it.js |     100 |      100 |     100 |     100 |                   
  index.test-ut.js |     100 |      100 |     100 |     100 |                   
 src/eventManager  |   43.75 |     12.5 |     100 |   43.75 |                   
  eventListener.js |   43.75 |     12.5 |     100 |   43.75 | 12-25             
 ...profileManager |   53.85 |     12.5 |   44.44 |   53.85 |                   
  index.js         |   41.46 |     12.5 |   44.44 |   41.46 | ...9,73-82,98,114 
  router.js        |     100 |      100 |     100 |     100 |                   
 src/subsCrypt     |   63.03 |       50 |   59.62 |   63.03 |                   
  index.js         |   60.71 |       50 |   58.82 |   60.71 | ...67-270,283-287 
  router.js        |     100 |      100 |     100 |     100 |                   
 src/subscriptions |     100 |      100 |     100 |     100 |                   
  index.js         |     100 |      100 |     100 |     100 |                   
  router.js        |     100 |      100 |     100 |     100 |                   
-------------------|---------|----------|---------|---------|-------------------
</pre>
